version: "3"
services:
  go-mysql:
    image: mariadb:latest
    container_name: go_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - go_mysql:/var/lib/mysql
    networks:
      - go_mysql_network

  go-adminer:
    image: adminer:latest
    container_name: go_adminer
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - go-mysql
    environment:
      ADMINER_DEFAULT_SERVER: go-mysql
    networks:
      - go_mysql_network

volumes:
  go_mysql:

# Networks to be created to facilitate communication between containers
networks:
  go_mysql_network:
    driver: bridge
