### Get all post
GET http://localhost:8070/post
Content-Type: application/json

### Get an post
GET http://localhost:8070/post/3
Content-Type: application/json

### Create a new post
POST http://localhost:8070/post
Content-Type: application/json

{
    "title": "Post title new",
    "content": "Post content new"
}

### Update a post
PUT http://localhost:8070/post/10
Content-Type: application/json

{
    "title": "Post title edited 2",
    "content": "Post content edit"
}

### Delete a post
DELETE http://localhost:8070/post/15
Content-Type: application/json