### Get all post
GET http://localhost:8070/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjEyZDBmNGQzLWRiN2QtNGQxZC1iOGQ1LTIzYmEyNjQxZjNlMSIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzNDQ1OTE0NiwidXNlcl9pZCI6N30.15mcp7xLaCBzGy113gJf2-ZQT4XH5n1bS-5Nvy1WB3c

### Get an post
GET http://localhost:8070/post/1
Content-Type: application/json

### Create a new post
POST http://localhost:8070/post
Content-Type: application/json

{
    "title": "Post title new",
    "content": "Post content new",
    "published": true,
    "authorId": 1
}

### Update a post
PUT http://localhost:8070/post/2
Content-Type: application/json

{
    "title": "Post title edited",
    "content": "Post content edit",
    "published": true,
    "authorId": 1
}

### Delete a post
DELETE http://localhost:8070/post/11
Content-Type: application/json

### Get all user
GET http://localhost:8070/user
Content-Type: application/json

### Get an user
GET http://localhost:8070/user/1
Content-Type: application/json

### Create a new user
POST http://localhost:8070/user
Content-Type: application/json

{
    "email": "1@g.com",
    "name": "admin",
    "pass": "admin",
    "role": "admin"
}

### Update a user
PUT http://localhost:8070/user/2
Content-Type: application/json

{
    "email": "2@g.com",
    "name": "user2",
    "pass": "user1"
}

### Delete a user
DELETE http://localhost:8070/user/11
Content-Type: application/json

### Login
POST http://localhost:8070/login
Content-Type: application/json

{
    "email": "1@g.com",
    "pass": "admin"
}

### Register
POST http://localhost:8070/register
Content-Type: application/json

{
    "email": "13@gmail.com",
    "name": "nham",
    "pass": "1234"
}

### Get token by refresh token
POST http://localhost:8070/token/refresh
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzUwNTg5ODUsInJlZnJlc2hfdXVpZCI6ImFiYzdkYTRlLTNkMWQtNGEwMS1iMjgyLWNiOTRlMTk4ZGU4MyIsInVzZXJfaWQiOjd9.4k-DW_O1L4y5Hlk56ZElFu_qJaQAWPBqO4dqfQos9VE"
}